---

- name: Check Server Certificate
  ansible.builtin.stat:
    path: '{{ cert_dir }}/intermediate/certs/{{ server_common_name }}.cert.pem'
  register: server_cert_stat

- name: Server Private Key | {{ server_common_name }}
  include_tasks: tasks/tls_privatekey.yml
  vars:
    privatekey_path: '{{ cert_dir }}/intermediate/private/{{ server_common_name }}.key.pem'
    privatekey_passphrase: '{{ passphrase }}'
  when: not server_cert_stat.stat.exists|bool

- name: Server CSR | {{ server_common_name }}
  include_tasks: tasks/tls_csr.yml
  vars:
    csr_path: '{{ cert_dir }}/intermediate/csr/{{ server_common_name }}.csr.pem'
    csr_common_name: '{{ server_common_name }}'
    csr_privatekey_path: '{{ cert_dir }}/intermediate/private/{{ server_common_name }}.key.pem'
    csr_privatekey_passphrase: '{{ passphrase }}'
    csr_basic_constraints: 'CA:FALSE'
    csr_basic_constraints_critical: true
    csr_key_usage:
      - nonRepudiation
      - digitalSignature
      - keyEncipherment
    csr_key_usage_critical: yes
    csr_extended_key_usage:
      - serverAuth
    csr_extended_key_usage_critical: true
    csr_subject_alt_name: '{{ server_subject_alt_name }}'
    #csr_authority_cert_serial_number:
    #csr_authority_cert_issuer:
    #csr_authority_key_identifier:
    #csr_subject_key_identifier:
    csr_email_address: '{{ dn.email_address }}'
    csr_country_name: '{{ dn.country_name }}'
    csr_locality_name: '{{ dn.locality_name }}'
    csr_state_or_province_name: '{{ dn.state_or_province_name }}'
    csr_organization_name: '{{ dn.organization_name }}'
    csr_organizational_unit_name: '{{ dn.organizational_unit_name }}'
  when: not server_cert_stat.stat.exists|bool

- name: Server Certificate | {{ server_common_name }}
  include_tasks: tasks/tls_certificate.yml
  vars:
    certificate_path: '{{ cert_dir }}/intermediate/certs/{{ server_common_name }}.cert.pem'
    certificate_csr_path: '{{ cert_dir }}/intermediate/csr/{{ server_common_name }}.csr.pem'
    certificate_privatekey_path: '{{ cert_dir }}/intermediate/private/{{ server_common_name }}.key.pem'
    certificate_privatekey_passphrase: '{{ passphrase }}'
    certificate_provider: ownca
    certificate_expiration_warn: '{{ server_certificate_expiration_warn }}'
    certificate_expiration_crit: '{{ server_certificate_expiration_crit }}'
    certificate_ownca_not_after: '{{ server_certificate_ownca_not_after }}'
    certificate_ownca_not_before: '{{ server_certificate_ownca_not_before }}'
    certificate_ownca_path: '{{ cert_dir }}/intermediate/certs/intermediate.cert.pem'
    certificate_ownca_privatekey_path: '{{ cert_dir }}/intermediate/private/intermediate.key.pem'
    certificate_ownca_privatekey_passphrase: '{{ intermediate_passphrase }}'
  when: not server_cert_stat.stat.exists|bool or check_cert_validity|bool