---

- name: Check Client Certificate
  ansible.builtin.stat:
    path: '{{ cert_dir }}/intermediate/certs/{{ client_common_name }}.cert.pem'
  register: client_cert_stat

- name: Client Private Key | {{ client_common_name }}
  include_tasks: tasks/tls_privatekey.yml
  vars:
    privatekey_path: '{{ cert_dir }}/intermediate/private/{{ client_common_name }}.key.pem'
    privatekey_passphrase: '{{ passphrase }}'
  when: not client_cert_stat.stat.exists|bool

- name: Client CSR | {{ client_common_name }}
  include_tasks: tasks/tls_csr.yml
  vars:
    csr_path: '{{ cert_dir }}/intermediate/csr/{{ client_common_name }}.csr.pem'
    csr_common_name: '{{ client_common_name }}'
    csr_privatekey_path: '{{ cert_dir }}/intermediate/private/{{ client_common_name }}.key.pem'
    csr_privatekey_passphrase: '{{ passphrase }}'
    csr_basic_constraints: 'CA:FALSE'
    csr_basic_constraints_critical: true
    csr_key_usage:
      - nonRepudiation
      - digitalSignature
      - keyEncipherment
    csr_key_usage_critical: yes
    csr_extended_key_usage:
      - clientAuth
    csr_extended_key_usage_critical: true
    #csr_subject_alt_name:
    #csr_authority_cert_serial_number:
    #csr_authority_cert_issuer:
    #csr_authority_key_identifier:
    #csr_subject_key_identifier:
    csr_email_address: '{{ dn.email_address }}'
    csr_country_name: '{{ dn.country_name }}'
    csr_locality_name: '{{ dn.locality_name }}'
    csr_state_or_province_name: '{{ dn.state_or_province_name }}'
    csr_organization_name: '{{ dn.organization_name }}'
    csr_organizational_unit_name: '{{ dn.organizational_unit_name }}'
  when: not client_cert_stat.stat.exists|bool

- name: Client Certificate | {{ client_common_name }}
  include_tasks: tasks/tls_certificate.yml
  vars:
    certificate_path: '{{ cert_dir }}/intermediate/certs/{{ client_common_name }}.cert.pem'
    certificate_csr_path: '{{ cert_dir }}/intermediate/csr/{{ client_common_name }}.csr.pem'
    certificate_privatekey_path: '{{ cert_dir }}/intermediate/private/{{ client_common_name }}.key.pem'
    certificate_privatekey_passphrase: '{{ passphrase }}'
    certificate_provider: ownca
    certificate_expiration_warn: '{{ client_certificate_expiration_warn }}'
    certificate_expiration_crit: '{{ client_certificate_expiration_crit }}'
    certificate_ownca_not_after: '{{ client_certificate_ownca_not_after }}'
    certificate_ownca_not_before: '{{ client_certificate_ownca_not_before }}'
    certificate_ownca_path: '{{ cert_dir }}/intermediate/certs/intermediate.cert.pem'
    certificate_ownca_privatekey_path: '{{ cert_dir }}/intermediate/private/intermediate.key.pem'
    certificate_ownca_privatekey_passphrase: '{{ intermediate_passphrase }}'
  when: not client_cert_stat.stat.exists|bool or check_cert_validity|bool