---
- name: Converge
  hosts: all
  vars:
    cert_dir: example_certs
    server_hostnames:
      - servera.example.com
      - serverb.example.com
      - example.com
    client_hostnames:
      - client1.example.com
      - client2.example.com
  tasks:
    - name: "Include ss_ca"
      include_role:
        name: "ansible-role-ss_ca"